name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Fetch previous coverage
        id: previous-coverage
        run: |
          echo "Downloading previous coverage badges..."
          PREV_COVERAGE=$(curl -s https://raw.githubusercontent.com/${{ github.repository }}/badges/jacoco.svg | grep -oP '(?<=>)[0-9]+(?=%)' || echo "100")
          PREV_BRANCHES=$(curl -s https://raw.githubusercontent.com/${{ github.repository }}/badges/jacoco-branches.svg | grep -oP '(?<=>)[0-9]+(?=%)' || echo "100")
          echo "prev_coverage=$PREV_COVERAGE" >> $GITHUB_OUTPUT
          echo "prev_branches=$PREV_BRANCHES" >> $GITHUB_OUTPUT
          echo "Previous coverage: $PREV_COVERAGE%, Branches: $PREV_BRANCHES%"

      - name: Setting Permissions
        run: chmod a+x gradlew
      - name: Build and Test with Coverage
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build test jacocoTestReport

      - name: Generate JaCoCo Badges
        uses: cicirello/jacoco-badge-generator@v2.9.0
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true
          fail-if-coverage-less-than: ${{ steps.previous-coverage.outputs.prev_coverage }}
          fail-if-branches-less-than: ${{ steps.previous-coverage.outputs.prev_branches }}
          fail-on-coverage-decrease: true
          fail-on-branches-decrease: true

  build_and_publish_docker_image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest
